import { MemberProfile, Project, Transaction, Role, ProjectStatus, FeeStatus, BankAccount, ChatMessage } from './types';

export const INITIAL_USERS: MemberProfile[] = [
  {
    id: 1,
    name: 'Admin User',
    cpf: '111.111.111-11',
    address: '123 Admin St, City',
    phone: '(11) 91111-1111',
    email: 'admin@community.com',
    password: 'password123',
    joinDate: '2020-01-15',
    role: Role.Admin,
    avatarUrl: 'https://picsum.photos/seed/admin/200',
    bannerUrl: 'https://picsum.photos/seed/banner1/1000/300',
    fees: [
      { month: 'Janeiro', year: 2024, status: FeeStatus.Paid, amount: 50 },
      { month: 'Fevereiro', year: 2024, status: FeeStatus.Paid, amount: 50 },
      { month: 'Março', year: 2024, status: FeeStatus.Paid, amount: 50 },
    ],
  },
  {
    id: 2,
    name: 'Gerente de Projetos Silva',
    cpf: '222.222.222-22',
    address: '456 Manager Ave, City',
    phone: '(11) 92222-2222',
    email: 'manager@community.com',
    password: 'password123',
    joinDate: '2021-03-20',
    role: Role.ProjectManager,
    avatarUrl: 'https://picsum.photos/seed/manager/200',
    bannerUrl: 'https://picsum.photos/seed/banner2/1000/300',
    fees: [
      { month: 'Janeiro', year: 2024, status: FeeStatus.Paid, amount: 50 },
      { month: 'Fevereiro', year: 2024, status: FeeStatus.Paid, amount: 50 },
      { month: 'Março', year: 2024, status: FeeStatus.Paid, amount: 50 },
    ],
  },
  {
    id: 3,
    name: 'Associado Oliveira',
    cpf: '333.333.333-33',
    address: '789 Member Rd, City',
    phone: '(11) 93333-3333',
    email: 'member@community.com',
    password: 'password123',
    joinDate: '2022-07-01',
    role: Role.Member,
    avatarUrl: 'https://picsum.photos/seed/member1/200',
    bannerUrl: 'https://picsum.photos/seed/banner3/1000/300',
    fees: [
      { month: 'Janeiro', year: 2024, status: FeeStatus.Paid, amount: 50 },
      { month: 'Fevereiro', year: 2024, status: FeeStatus.Paid, amount: 50 },
      { month: 'Março', year: 2024, status: FeeStatus.Pending, amount: 50 },
    ],
  },
  {
    id: 4,
    name: 'Associada Souza',
    cpf: '444.444.444-44',
    address: '101 Member Ln, City',
    phone: '(11) 94444-4444',
    email: 'member2@community.com',
    password: 'password123',
    joinDate: '2023-11-10',
    role: Role.Member,
    avatarUrl: 'https://picsum.photos/seed/member2/200',
    bannerUrl: 'https://picsum.photos/seed/banner4/1000/300',
    fees: [
      { month: 'Janeiro', year: 2024, status: FeeStatus.Paid, amount: 50 },
      { month: 'Fevereiro', year: 2024, status: FeeStatus.Pending, amount: 50 },
      { month: 'Março', year: 2024, status: FeeStatus.Pending, amount: 50 },
    ],
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 1,
    name: 'Horta Comunitária',
    description: 'Criação e manutenção de uma horta comunitária no bairro.',
    managerId: 2,
    startDate: '2024-02-01',
    endDate: '2024-12-31',
    budget: 5000,
    status: ProjectStatus.InProgress,
    files: [],
  },
  {
    id: 2,
    name: 'Festa Junina 2024',
    description: 'Organização da festa junina anual da comunidade.',
    managerId: 2,
    startDate: '2024-05-01',
    endDate: '2024-06-30',
    budget: 15000,
    status: ProjectStatus.InProgress,
    files: ['orcamento_barracas.pdf', 'contrato_banda.pdf'],
  },
  {
    id: 3,
    name: 'Reforma da Sede',
    description: 'Reforma e pintura da sede da associação.',
    managerId: 1,
    startDate: '2023-09-01',
    endDate: '2023-11-30',
    budget: 25000,
    status: ProjectStatus.Completed,
    files: ['nota_fiscal_tintas.pdf'],
  },
  {
    id: 4,
    name: 'Aulas de Reforço',
    description: 'Projeto de aulas de reforço escolar para crianças da comunidade.',
    managerId: 2,
    startDate: '2024-08-01',
    endDate: '2024-12-15',
    budget: 8000,
    status: ProjectStatus.Suspended,
    files: [],
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
    { id: 1, description: 'Mensalidade Janeiro', amount: 200, type: 'Receita', category: 'Mensalidades', date: '2024-01-10' },
    { id: 2, description: 'Doação Empresa X', amount: 1000, type: 'Receita', category: 'Doações', date: '2024-01-15' },
    { id: 3, description: 'Material de escritório', amount: 150, type: 'Despesa', category: 'Administrativo', date: '2024-01-20' },
    { id: 4, description: 'Mensalidade Fevereiro', amount: 150, type: 'Receita', category: 'Mensalidades', date: '2024-02-10' },
    { id: 5, description: 'Conta de luz', amount: 250, type: 'Despesa', category: 'Contas Fixas', date: '2024-02-25' },
    { id: 6, description: 'Insumos Horta', amount: 800, type: 'Despesa', category: 'Projetos', date: '2024-03-05' },
    { id: 7, description: 'Mensalidade Março', amount: 100, type: 'Receita', category: 'Mensalidades', date: '2024-03-10' },
];

export const INITIAL_BANK_ACCOUNTS: BankAccount[] = [
    { id: 1, name: 'Banco Principal', agency: '0001', account: '123456-7', type: 'Conta Corrente' },
    { id: 2, name: 'Poupança Projetos', agency: '0001', account: '765432-1', type: 'Conta Poupança' },
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
    {
        id: 1,
        senderId: 2,
        senderName: 'Gerente de Projetos Silva',
        senderAvatarUrl: 'https://picsum.photos/seed/manager/200',
        text: 'Olá pessoal! Lembrete amigável sobre nossa reunião do projeto da Horta Comunitária amanhã às 10h.',
        timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
    {
        id: 2,
        senderId: 4,
        senderName: 'Associada Souza',
        senderAvatarUrl: 'https://picsum.photos/seed/member2/200',
        text: 'Confirmado! Estarei lá. Alguém sabe se precisamos levar algo?',
        timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    },
     {
        id: 3,
        senderId: 3,
        senderName: 'Associado Oliveira',
        senderAvatarUrl: 'https://picsum.photos/seed/member1/200',
        text: 'Acho que só boas ideias já são o suficiente! 😄',
        timestamp: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
    },
];